//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputManagement/IInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @IInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @IInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""IInput"",
    ""maps"": [
        {
            ""name"": ""LController"",
            ""id"": ""daa13bf6-5ff4-4c3b-8386-2a47d6b5bc7a"",
            ""actions"": [
                {
                    ""name"": ""Grip"",
                    ""type"": ""Value"",
                    ""id"": ""3234ff04-45fb-4f37-9903-61d892bd4b19"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Trigger"",
                    ""type"": ""Value"",
                    ""id"": ""b6d84b76-7852-4bb7-99a1-4605a507dd23"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""4112dec8-b350-43d9-8c3a-33ee85c644b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondayButton"",
                    ""type"": ""Button"",
                    ""id"": ""4b2df4c3-42f7-4ad0-82b0-e77b3af7c1fe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryTouched"",
                    ""type"": ""Button"",
                    ""id"": ""e2018f43-e854-4b5d-b53c-2fb4d83a186d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryTouched"",
                    ""type"": ""Button"",
                    ""id"": ""72950d74-2659-422b-aaad-54c66abf40e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stick"",
                    ""type"": ""Value"",
                    ""id"": ""33cc33c2-fcbe-46de-b62d-39a4800df906"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerTouched"",
                    ""type"": ""Button"",
                    ""id"": ""95c5cf6a-1a7b-4f5a-8ba6-9657cc24437d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StickClicked"",
                    ""type"": ""Button"",
                    ""id"": ""e9e2c67b-2a43-406e-b7fb-814a3d24a532"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StickTouched"",
                    ""type"": ""Button"",
                    ""id"": ""35f230b6-7418-4a76-871e-68c138e92d9d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4e39e5f3-7ef5-4643-ba8b-9c259c858c76"",
                    ""path"": ""<XRController>{LeftHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb989693-c535-4dc0-ae17-605d75af3323"",
                    ""path"": ""<XRController>{LeftHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""557deca7-ddb7-4d52-aa0a-3c518d4fe33d"",
                    ""path"": ""<XRController>{LeftHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d73374a2-7b43-4470-9f9f-269ddd5ec561"",
                    ""path"": ""<XRController>{LeftHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondayButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4aa572f-1192-4a42-a3f3-3a9789fa645a"",
                    ""path"": ""<XRController>{LeftHand}/primaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4e385513-e1c3-4a83-9817-2ccd39a59e29"",
                    ""path"": ""<XRController>{LeftHand}/secondaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a41c4168-8ee4-4557-b035-cce4768358e0"",
                    ""path"": ""<XRController>{LeftHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bd6e9fe-dcba-40bf-9309-cdc72e64ff61"",
                    ""path"": ""<XRController>{LeftHand}/touchpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71324a3b-87b2-4967-ad90-006a877efd0c"",
                    ""path"": ""<XRController>{LeftHand}/trackpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22d928c1-0934-424c-9d30-da36f12a8a0e"",
                    ""path"": ""<XRController>{LeftHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a76ac97c-884a-4bea-b12d-7092bb1496ce"",
                    ""path"": ""<XRController>{LeftHand}/triggerTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a4f47bb-1e9b-4338-aac9-8dbc6494bd5f"",
                    ""path"": ""<XRController>{LeftHand}/touchpadClick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickClicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e54c3d1b-2d67-4eb2-a60c-90b25b77c96d"",
                    ""path"": ""<XRController>{LeftHand}/trackpadPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickClicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eee640b0-eed9-48f6-b8ad-f332e3b36ff1"",
                    ""path"": ""<XRController>{LeftHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickClicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""363bf581-8281-497b-a4a2-0bc2ad992f15"",
                    ""path"": ""<XRController>{LeftHand}/touchpadTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3b33630-c2f3-4c60-85de-d795a4634af7"",
                    ""path"": ""<XRController>{LeftHand}/trackpadTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4afe05d6-c53b-4271-af1c-0e14b5538072"",
                    ""path"": ""<XRController>{LeftHand}/thumbstickTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""RController"",
            ""id"": ""53c29d2d-86f6-4440-bc67-b39097d0cb7c"",
            ""actions"": [
                {
                    ""name"": ""Grip"",
                    ""type"": ""Value"",
                    ""id"": ""d7360090-75dd-45e2-b486-e5e3a14338c1"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Trigger"",
                    ""type"": ""Value"",
                    ""id"": ""c6700dad-1747-44da-8638-f7b945723835"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryButton"",
                    ""type"": ""Button"",
                    ""id"": ""95836afe-eb55-4812-bde4-a0ce17aa8d56"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondayButton"",
                    ""type"": ""Button"",
                    ""id"": ""15e1c081-4bae-4e14-a0a4-c704118c679d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryTouched"",
                    ""type"": ""Button"",
                    ""id"": ""82896651-f657-4105-8ebf-78d553629d04"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SecondaryTouched"",
                    ""type"": ""Button"",
                    ""id"": ""af69f18f-66ff-4d98-b86a-2fa7ec11527e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stick"",
                    ""type"": ""Value"",
                    ""id"": ""11d010a5-4476-40b7-adec-e88ed594e135"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerTouched"",
                    ""type"": ""Button"",
                    ""id"": ""33047e94-ce81-42bc-a3fc-bcdad1232405"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StickClicked"",
                    ""type"": ""Button"",
                    ""id"": ""d74ad0f0-13f0-4d3c-9ca2-2600cc8cb727"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StickTouched"",
                    ""type"": ""Button"",
                    ""id"": ""07c914f2-2a3c-42cd-8f00-d9c30582ecdd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7c809c6c-3d9c-413b-a96f-07f9b83ad71c"",
                    ""path"": ""<XRController>{RightHand}/grip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Grip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f55cf5e6-2b0d-4a69-a48b-348cd2b134f7"",
                    ""path"": ""<XRController>{RightHand}/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1edab8b-4ffe-440c-ae16-c5606bb04e3f"",
                    ""path"": ""<XRController>{RightHand}/primaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4b5d5928-9b1a-44cf-b650-2f7793e20e91"",
                    ""path"": ""<XRController>{RightHand}/secondaryButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondayButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91f648b3-3c0b-4f9f-b14a-5d97edfe93b6"",
                    ""path"": ""<XRController>{RightHand}/primaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b49fae81-c292-491d-8337-c54e0ee846db"",
                    ""path"": ""<XRController>{RightHand}/secondaryTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba64cffa-ec10-434d-82e3-93b6d0f7ea7f"",
                    ""path"": ""<XRController>{RightHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cf3b7232-09eb-4a56-8876-4c30d983902f"",
                    ""path"": ""<XRController>{RightHand}/touchpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88946cef-1386-4f0f-bcef-1eb904ee03ec"",
                    ""path"": ""<XRController>{RightHand}/trackpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""480724de-cd28-4e63-82b9-5716aa7458e9"",
                    ""path"": ""<XRController>{RightHand}/thumbstick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed29c197-f564-4446-91d5-118faca81278"",
                    ""path"": ""<XRController>{RightHand}/triggerTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cebb2f51-6a4c-4f10-96fe-ce78b04c276d"",
                    ""path"": ""<XRController>{RightHand}/touchpadClick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickClicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b42225cf-0446-4893-bf5d-a51104fba242"",
                    ""path"": ""<XRController>{RightHand}/trackpadPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickClicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b82b2895-d5d9-4575-93f5-e6180661f55f"",
                    ""path"": ""<XRController>{RightHand}/thumbstickClicked"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickClicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""083939ae-eff1-4f39-bf2f-4792efc1efe7"",
                    ""path"": ""<XRController>{RightHand}/touchpadTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2b2ab4f-77ab-4689-be86-ad53f567fa41"",
                    ""path"": ""<XRController>{RightHand}/trackpadTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b44a3539-c8de-46c0-89e4-d6bda162889a"",
                    ""path"": ""<XRController>{RightHand}/thumbstickTouched"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StickTouched"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Special"",
            ""id"": ""1e6ccce8-c52f-4c5e-ac1f-e5a2bf4388b7"",
            ""actions"": [
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""3d76b8d3-e812-4428-a1e0-cd687c56a45d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Recentered"",
                    ""type"": ""Button"",
                    ""id"": ""a94bbb72-a40e-4f6f-ac0d-cfaa16c78935"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b7364389-2c95-445a-b392-12c2ef544bd9"",
                    ""path"": ""<XRController>{RightHand}/menu"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c568ce29-b0a5-47eb-9841-eca0480fb7d8"",
                    ""path"": ""<XRController>{RightHand}/home"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc80a9a2-69a2-4d88-9bac-22b63580eda1"",
                    ""path"": ""<XRController>{LeftHand}/menu"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04d28a7b-c75d-4190-9426-558ff9692d7c"",
                    ""path"": ""<XRController>{LeftHand}/home"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9d208b6-19a2-4958-b322-a5b361c3d081"",
                    ""path"": ""<XRController>{LeftHand}/recentered"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Recentered"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25b25189-ebad-4f53-bd24-6b917299f8b9"",
                    ""path"": ""<XRController>{RightHand}/recentered"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Recentered"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // LController
        m_LController = asset.FindActionMap("LController", throwIfNotFound: true);
        m_LController_Grip = m_LController.FindAction("Grip", throwIfNotFound: true);
        m_LController_Trigger = m_LController.FindAction("Trigger", throwIfNotFound: true);
        m_LController_PrimaryButton = m_LController.FindAction("PrimaryButton", throwIfNotFound: true);
        m_LController_SecondayButton = m_LController.FindAction("SecondayButton", throwIfNotFound: true);
        m_LController_PrimaryTouched = m_LController.FindAction("PrimaryTouched", throwIfNotFound: true);
        m_LController_SecondaryTouched = m_LController.FindAction("SecondaryTouched", throwIfNotFound: true);
        m_LController_Stick = m_LController.FindAction("Stick", throwIfNotFound: true);
        m_LController_TriggerTouched = m_LController.FindAction("TriggerTouched", throwIfNotFound: true);
        m_LController_StickClicked = m_LController.FindAction("StickClicked", throwIfNotFound: true);
        m_LController_StickTouched = m_LController.FindAction("StickTouched", throwIfNotFound: true);
        // RController
        m_RController = asset.FindActionMap("RController", throwIfNotFound: true);
        m_RController_Grip = m_RController.FindAction("Grip", throwIfNotFound: true);
        m_RController_Trigger = m_RController.FindAction("Trigger", throwIfNotFound: true);
        m_RController_PrimaryButton = m_RController.FindAction("PrimaryButton", throwIfNotFound: true);
        m_RController_SecondayButton = m_RController.FindAction("SecondayButton", throwIfNotFound: true);
        m_RController_PrimaryTouched = m_RController.FindAction("PrimaryTouched", throwIfNotFound: true);
        m_RController_SecondaryTouched = m_RController.FindAction("SecondaryTouched", throwIfNotFound: true);
        m_RController_Stick = m_RController.FindAction("Stick", throwIfNotFound: true);
        m_RController_TriggerTouched = m_RController.FindAction("TriggerTouched", throwIfNotFound: true);
        m_RController_StickClicked = m_RController.FindAction("StickClicked", throwIfNotFound: true);
        m_RController_StickTouched = m_RController.FindAction("StickTouched", throwIfNotFound: true);
        // Special
        m_Special = asset.FindActionMap("Special", throwIfNotFound: true);
        m_Special_Menu = m_Special.FindAction("Menu", throwIfNotFound: true);
        m_Special_Recentered = m_Special.FindAction("Recentered", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // LController
    private readonly InputActionMap m_LController;
    private List<ILControllerActions> m_LControllerActionsCallbackInterfaces = new List<ILControllerActions>();
    private readonly InputAction m_LController_Grip;
    private readonly InputAction m_LController_Trigger;
    private readonly InputAction m_LController_PrimaryButton;
    private readonly InputAction m_LController_SecondayButton;
    private readonly InputAction m_LController_PrimaryTouched;
    private readonly InputAction m_LController_SecondaryTouched;
    private readonly InputAction m_LController_Stick;
    private readonly InputAction m_LController_TriggerTouched;
    private readonly InputAction m_LController_StickClicked;
    private readonly InputAction m_LController_StickTouched;
    public struct LControllerActions
    {
        private @IInput m_Wrapper;
        public LControllerActions(@IInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Grip => m_Wrapper.m_LController_Grip;
        public InputAction @Trigger => m_Wrapper.m_LController_Trigger;
        public InputAction @PrimaryButton => m_Wrapper.m_LController_PrimaryButton;
        public InputAction @SecondayButton => m_Wrapper.m_LController_SecondayButton;
        public InputAction @PrimaryTouched => m_Wrapper.m_LController_PrimaryTouched;
        public InputAction @SecondaryTouched => m_Wrapper.m_LController_SecondaryTouched;
        public InputAction @Stick => m_Wrapper.m_LController_Stick;
        public InputAction @TriggerTouched => m_Wrapper.m_LController_TriggerTouched;
        public InputAction @StickClicked => m_Wrapper.m_LController_StickClicked;
        public InputAction @StickTouched => m_Wrapper.m_LController_StickTouched;
        public InputActionMap Get() { return m_Wrapper.m_LController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LControllerActions set) { return set.Get(); }
        public void AddCallbacks(ILControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_LControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LControllerActionsCallbackInterfaces.Add(instance);
            @Grip.started += instance.OnGrip;
            @Grip.performed += instance.OnGrip;
            @Grip.canceled += instance.OnGrip;
            @Trigger.started += instance.OnTrigger;
            @Trigger.performed += instance.OnTrigger;
            @Trigger.canceled += instance.OnTrigger;
            @PrimaryButton.started += instance.OnPrimaryButton;
            @PrimaryButton.performed += instance.OnPrimaryButton;
            @PrimaryButton.canceled += instance.OnPrimaryButton;
            @SecondayButton.started += instance.OnSecondayButton;
            @SecondayButton.performed += instance.OnSecondayButton;
            @SecondayButton.canceled += instance.OnSecondayButton;
            @PrimaryTouched.started += instance.OnPrimaryTouched;
            @PrimaryTouched.performed += instance.OnPrimaryTouched;
            @PrimaryTouched.canceled += instance.OnPrimaryTouched;
            @SecondaryTouched.started += instance.OnSecondaryTouched;
            @SecondaryTouched.performed += instance.OnSecondaryTouched;
            @SecondaryTouched.canceled += instance.OnSecondaryTouched;
            @Stick.started += instance.OnStick;
            @Stick.performed += instance.OnStick;
            @Stick.canceled += instance.OnStick;
            @TriggerTouched.started += instance.OnTriggerTouched;
            @TriggerTouched.performed += instance.OnTriggerTouched;
            @TriggerTouched.canceled += instance.OnTriggerTouched;
            @StickClicked.started += instance.OnStickClicked;
            @StickClicked.performed += instance.OnStickClicked;
            @StickClicked.canceled += instance.OnStickClicked;
            @StickTouched.started += instance.OnStickTouched;
            @StickTouched.performed += instance.OnStickTouched;
            @StickTouched.canceled += instance.OnStickTouched;
        }

        private void UnregisterCallbacks(ILControllerActions instance)
        {
            @Grip.started -= instance.OnGrip;
            @Grip.performed -= instance.OnGrip;
            @Grip.canceled -= instance.OnGrip;
            @Trigger.started -= instance.OnTrigger;
            @Trigger.performed -= instance.OnTrigger;
            @Trigger.canceled -= instance.OnTrigger;
            @PrimaryButton.started -= instance.OnPrimaryButton;
            @PrimaryButton.performed -= instance.OnPrimaryButton;
            @PrimaryButton.canceled -= instance.OnPrimaryButton;
            @SecondayButton.started -= instance.OnSecondayButton;
            @SecondayButton.performed -= instance.OnSecondayButton;
            @SecondayButton.canceled -= instance.OnSecondayButton;
            @PrimaryTouched.started -= instance.OnPrimaryTouched;
            @PrimaryTouched.performed -= instance.OnPrimaryTouched;
            @PrimaryTouched.canceled -= instance.OnPrimaryTouched;
            @SecondaryTouched.started -= instance.OnSecondaryTouched;
            @SecondaryTouched.performed -= instance.OnSecondaryTouched;
            @SecondaryTouched.canceled -= instance.OnSecondaryTouched;
            @Stick.started -= instance.OnStick;
            @Stick.performed -= instance.OnStick;
            @Stick.canceled -= instance.OnStick;
            @TriggerTouched.started -= instance.OnTriggerTouched;
            @TriggerTouched.performed -= instance.OnTriggerTouched;
            @TriggerTouched.canceled -= instance.OnTriggerTouched;
            @StickClicked.started -= instance.OnStickClicked;
            @StickClicked.performed -= instance.OnStickClicked;
            @StickClicked.canceled -= instance.OnStickClicked;
            @StickTouched.started -= instance.OnStickTouched;
            @StickTouched.performed -= instance.OnStickTouched;
            @StickTouched.canceled -= instance.OnStickTouched;
        }

        public void RemoveCallbacks(ILControllerActions instance)
        {
            if (m_Wrapper.m_LControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_LControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LControllerActions @LController => new LControllerActions(this);

    // RController
    private readonly InputActionMap m_RController;
    private List<IRControllerActions> m_RControllerActionsCallbackInterfaces = new List<IRControllerActions>();
    private readonly InputAction m_RController_Grip;
    private readonly InputAction m_RController_Trigger;
    private readonly InputAction m_RController_PrimaryButton;
    private readonly InputAction m_RController_SecondayButton;
    private readonly InputAction m_RController_PrimaryTouched;
    private readonly InputAction m_RController_SecondaryTouched;
    private readonly InputAction m_RController_Stick;
    private readonly InputAction m_RController_TriggerTouched;
    private readonly InputAction m_RController_StickClicked;
    private readonly InputAction m_RController_StickTouched;
    public struct RControllerActions
    {
        private @IInput m_Wrapper;
        public RControllerActions(@IInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Grip => m_Wrapper.m_RController_Grip;
        public InputAction @Trigger => m_Wrapper.m_RController_Trigger;
        public InputAction @PrimaryButton => m_Wrapper.m_RController_PrimaryButton;
        public InputAction @SecondayButton => m_Wrapper.m_RController_SecondayButton;
        public InputAction @PrimaryTouched => m_Wrapper.m_RController_PrimaryTouched;
        public InputAction @SecondaryTouched => m_Wrapper.m_RController_SecondaryTouched;
        public InputAction @Stick => m_Wrapper.m_RController_Stick;
        public InputAction @TriggerTouched => m_Wrapper.m_RController_TriggerTouched;
        public InputAction @StickClicked => m_Wrapper.m_RController_StickClicked;
        public InputAction @StickTouched => m_Wrapper.m_RController_StickTouched;
        public InputActionMap Get() { return m_Wrapper.m_RController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RControllerActions set) { return set.Get(); }
        public void AddCallbacks(IRControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_RControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RControllerActionsCallbackInterfaces.Add(instance);
            @Grip.started += instance.OnGrip;
            @Grip.performed += instance.OnGrip;
            @Grip.canceled += instance.OnGrip;
            @Trigger.started += instance.OnTrigger;
            @Trigger.performed += instance.OnTrigger;
            @Trigger.canceled += instance.OnTrigger;
            @PrimaryButton.started += instance.OnPrimaryButton;
            @PrimaryButton.performed += instance.OnPrimaryButton;
            @PrimaryButton.canceled += instance.OnPrimaryButton;
            @SecondayButton.started += instance.OnSecondayButton;
            @SecondayButton.performed += instance.OnSecondayButton;
            @SecondayButton.canceled += instance.OnSecondayButton;
            @PrimaryTouched.started += instance.OnPrimaryTouched;
            @PrimaryTouched.performed += instance.OnPrimaryTouched;
            @PrimaryTouched.canceled += instance.OnPrimaryTouched;
            @SecondaryTouched.started += instance.OnSecondaryTouched;
            @SecondaryTouched.performed += instance.OnSecondaryTouched;
            @SecondaryTouched.canceled += instance.OnSecondaryTouched;
            @Stick.started += instance.OnStick;
            @Stick.performed += instance.OnStick;
            @Stick.canceled += instance.OnStick;
            @TriggerTouched.started += instance.OnTriggerTouched;
            @TriggerTouched.performed += instance.OnTriggerTouched;
            @TriggerTouched.canceled += instance.OnTriggerTouched;
            @StickClicked.started += instance.OnStickClicked;
            @StickClicked.performed += instance.OnStickClicked;
            @StickClicked.canceled += instance.OnStickClicked;
            @StickTouched.started += instance.OnStickTouched;
            @StickTouched.performed += instance.OnStickTouched;
            @StickTouched.canceled += instance.OnStickTouched;
        }

        private void UnregisterCallbacks(IRControllerActions instance)
        {
            @Grip.started -= instance.OnGrip;
            @Grip.performed -= instance.OnGrip;
            @Grip.canceled -= instance.OnGrip;
            @Trigger.started -= instance.OnTrigger;
            @Trigger.performed -= instance.OnTrigger;
            @Trigger.canceled -= instance.OnTrigger;
            @PrimaryButton.started -= instance.OnPrimaryButton;
            @PrimaryButton.performed -= instance.OnPrimaryButton;
            @PrimaryButton.canceled -= instance.OnPrimaryButton;
            @SecondayButton.started -= instance.OnSecondayButton;
            @SecondayButton.performed -= instance.OnSecondayButton;
            @SecondayButton.canceled -= instance.OnSecondayButton;
            @PrimaryTouched.started -= instance.OnPrimaryTouched;
            @PrimaryTouched.performed -= instance.OnPrimaryTouched;
            @PrimaryTouched.canceled -= instance.OnPrimaryTouched;
            @SecondaryTouched.started -= instance.OnSecondaryTouched;
            @SecondaryTouched.performed -= instance.OnSecondaryTouched;
            @SecondaryTouched.canceled -= instance.OnSecondaryTouched;
            @Stick.started -= instance.OnStick;
            @Stick.performed -= instance.OnStick;
            @Stick.canceled -= instance.OnStick;
            @TriggerTouched.started -= instance.OnTriggerTouched;
            @TriggerTouched.performed -= instance.OnTriggerTouched;
            @TriggerTouched.canceled -= instance.OnTriggerTouched;
            @StickClicked.started -= instance.OnStickClicked;
            @StickClicked.performed -= instance.OnStickClicked;
            @StickClicked.canceled -= instance.OnStickClicked;
            @StickTouched.started -= instance.OnStickTouched;
            @StickTouched.performed -= instance.OnStickTouched;
            @StickTouched.canceled -= instance.OnStickTouched;
        }

        public void RemoveCallbacks(IRControllerActions instance)
        {
            if (m_Wrapper.m_RControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_RControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RControllerActions @RController => new RControllerActions(this);

    // Special
    private readonly InputActionMap m_Special;
    private List<ISpecialActions> m_SpecialActionsCallbackInterfaces = new List<ISpecialActions>();
    private readonly InputAction m_Special_Menu;
    private readonly InputAction m_Special_Recentered;
    public struct SpecialActions
    {
        private @IInput m_Wrapper;
        public SpecialActions(@IInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Menu => m_Wrapper.m_Special_Menu;
        public InputAction @Recentered => m_Wrapper.m_Special_Recentered;
        public InputActionMap Get() { return m_Wrapper.m_Special; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SpecialActions set) { return set.Get(); }
        public void AddCallbacks(ISpecialActions instance)
        {
            if (instance == null || m_Wrapper.m_SpecialActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SpecialActionsCallbackInterfaces.Add(instance);
            @Menu.started += instance.OnMenu;
            @Menu.performed += instance.OnMenu;
            @Menu.canceled += instance.OnMenu;
            @Recentered.started += instance.OnRecentered;
            @Recentered.performed += instance.OnRecentered;
            @Recentered.canceled += instance.OnRecentered;
        }

        private void UnregisterCallbacks(ISpecialActions instance)
        {
            @Menu.started -= instance.OnMenu;
            @Menu.performed -= instance.OnMenu;
            @Menu.canceled -= instance.OnMenu;
            @Recentered.started -= instance.OnRecentered;
            @Recentered.performed -= instance.OnRecentered;
            @Recentered.canceled -= instance.OnRecentered;
        }

        public void RemoveCallbacks(ISpecialActions instance)
        {
            if (m_Wrapper.m_SpecialActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISpecialActions instance)
        {
            foreach (var item in m_Wrapper.m_SpecialActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SpecialActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SpecialActions @Special => new SpecialActions(this);
    public interface ILControllerActions
    {
        void OnGrip(InputAction.CallbackContext context);
        void OnTrigger(InputAction.CallbackContext context);
        void OnPrimaryButton(InputAction.CallbackContext context);
        void OnSecondayButton(InputAction.CallbackContext context);
        void OnPrimaryTouched(InputAction.CallbackContext context);
        void OnSecondaryTouched(InputAction.CallbackContext context);
        void OnStick(InputAction.CallbackContext context);
        void OnTriggerTouched(InputAction.CallbackContext context);
        void OnStickClicked(InputAction.CallbackContext context);
        void OnStickTouched(InputAction.CallbackContext context);
    }
    public interface IRControllerActions
    {
        void OnGrip(InputAction.CallbackContext context);
        void OnTrigger(InputAction.CallbackContext context);
        void OnPrimaryButton(InputAction.CallbackContext context);
        void OnSecondayButton(InputAction.CallbackContext context);
        void OnPrimaryTouched(InputAction.CallbackContext context);
        void OnSecondaryTouched(InputAction.CallbackContext context);
        void OnStick(InputAction.CallbackContext context);
        void OnTriggerTouched(InputAction.CallbackContext context);
        void OnStickClicked(InputAction.CallbackContext context);
        void OnStickTouched(InputAction.CallbackContext context);
    }
    public interface ISpecialActions
    {
        void OnMenu(InputAction.CallbackContext context);
        void OnRecentered(InputAction.CallbackContext context);
    }
}
